---
version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      TDD__SPARQLENDPOINT_URL: "http://sparqlendpoint:3030/things/"
    depends_on:
      - sparqlendpoint
  sparqlendpoint:
    image: "secoresearch/fuseki:latest"
    environment:
      ENABLE_UPLOAD: "true"
      ADMIN_PASSWORD: "password"
      ASSEMBLER: "/fuseki-base/configuration/things.ttl"
    volumes:
      - "./fuseki-docker/configuration:/fuseki-base/configuration"
      - "./fuseki-docker/databases:/fuseki-base/databases"
      - "./fuseki-docker/config.ttl:/fuseki-base/config.ttl"
