---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sparqlendpoint-configuration
  name: sparqlendpoint-configuration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
