---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sparqlendpoint-config
  name: sparqlendpoint-config
data:
  ttl-content: '
    @prefix fuseki:  <http://jena.apache.org/fuseki#> .
    @prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
    [] rdf:type fuseki:Server ;
        ja:loadClass "fi.seco.silk.arq.SilkFunctions".
'
